version: 2

before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'

  binary: '{{ .ProjectName }}'
  main: cmd/subfinder/main.go

archives:
- formats:
    - zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256

announce:
  slack:
    enabled: true
    channel: '#release'
    username: GoReleaser
    message_template: 'New Release: {{ .ProjectName }} {{.Tag}} is published! Check it out at {{ .ReleaseURL }}'

  discord:
    enabled: true
    message_template: '**New Release: {{ .ProjectName }} {{.Tag}}** is published! Check it out at {{ .ReleaseURL }}'
