name: 🔨 Release Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  release-test:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      
      - name: release test
        uses: goreleaser/goreleaser-action@v4
        with:
          args: "release --clean --snapshot"
          version: latest
